### ISSUE TITLE
Tag selection by backspace key for empty input line not working (Chrome)

### ISSUE THREAD

**Issue by schleimschein** [Wikiki/bulma-tagsinput#11]
### Issue
If the caret of the input line is at the very start and no tag is selected, pressing the backspace key won't select the first tag left to the input line for Chrome (63.0 Developer Build).
It may be that this is only the case if the proposed fix of [Issue #6: Selecting and deleting tags via keys not working in Chrome](#6) is applied to the `keypress` EventListener by changing `keypress` to `keydown`.

### Possible fix
In tagsinput.js, the `caretAtStart(el)` function should take an input element as argument, not a `keydown` event (probably also not the `keypress` event, I can't test this at the moment). It was sufficient for me to change the `atStart` variables in the `init()` and the `addTag()` functions
from
`atStart = this.caretAtStart(e);`     (e is the `keydown`  EventListener Listener)
 to
`atStart = this.caretAtStart(this.input);` .

**Comment by Wikiki** [comment]
Fixed by #4d37ea5
