### ISSUE TITLE
how to use the Tagify class since last release (npm repo)

### ISSUE THREAD

**Issue by harpagon210** [Wikiki/bulma-tagsinput#17]
Hi,

Is there a way to use the Tagify class from this extension?
Since the last release, I'm not able to create instances of it like this:

```javascript
import` Tagify from ...

new Tagify(element) 
```

Thanks

**Comment by Wikiki** [comment]
You don't have to do anything.
Just set attribute <code>type="tags"</code> to your input element and the Tagify component will be instantiated automatically.

**Comment by harpagon210** [comment]
the thing is that I receive the tags afterwards and I dynamically add the tags to the input value

**Comment by Wikiki** [comment]
ok then just use something like this:
```
let tagInputs = document.querySelectorAll('input[type="tags"]');
  [].forEach.call(tagInputs, function(tagInput) {
      new Tagify(tagInput);
  });
```

it's the code used by the plugin to auto-instantiate itself.

**Comment by harpagon210** [comment]
hmm, I don't see how this can work as the Tagify class is not accessible from outside of your js file (I'm not totally fluent in js I may be missing something...)

**Comment by Wikiki** [comment]
In the lzst version I've added <code>export default</code> too. (as you asked for other extensions).
It's not working ?

**Comment by harpagon210** [comment]
I'm using the npm repo 'bulma-extensions' and it seems that only the dist folders are available now and in the js file in this folder, the class Tagify is inside a global variable (so no export available)

**Comment by harpagon210** [comment]
the only way I found to make it works is by changing your js file

I replaced ``` var bulmaTagsinput = ``` by ```export const bulmaTagsinput = ```

this way I can use the extension like this:

```javascript
import {bulmaTagsinput} from 'bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput.js'

new bulmaTagsinput(...)
```

**Comment by Wikiki** [comment]
I'll have a look.

**Comment by harpagon210** [comment]
thanks for your help anyway ;)

**Comment by Wikiki** [comment]
Its seems to be related to the new Babel transpilation.
I'll see to find a way to keep <code>export const bulmaTagsinput</code> after the transpilation

**Comment by Wikiki** [comment]
I recompile using UMD output format instead IIFE.
Can you please try again ?

**Comment by harpagon210** [comment]
I can now import like this:

```javascript
import Tagify from 'bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput.js'
```
and use it like this:
```javascript
new Tagify(...)
```

thanks for your help!
also, could you update the npm repos?

**Comment by Wikiki** [comment]
NPM package updated.

**Comment by harpagon210** [comment]
could you update this repo as well please?
https://www.npmjs.com/package/bulma-extensions

Thanks for your work ;)
