### ISSUE TITLE
Breaking changes after 0.2.1

### ISSUE THREAD

**Issue by rathpc** [Wikiki/bulma-tagsinput#19]
It seems that after version 0.2.1 there were major breaking changes, specifically in the folder structure and naming of files. If anyone had bulma-tagsinput listed as version `^0.2.1` in their package.json and did a reinstall anytime after you added new patch versions their project would be completely broken due to invalid references to files which are now located behind a dist folder along with different naming conventions.

I just thought it was worth posting this here because such a change really should have warranted a "major" version bump to prevent npm from installing a version that breaks without adjusting for breaking changes. I know that other plugins you wrote, you had made similar folder structure and naming convention changes that would also cause the same issues. It might be helpful to document those breaking changes in your readme files for each plugin referencing version numbers that would be affected.

Thanks!

**Comment by Wikiki** [comment]
Hi,

thanks for your feedback.
You're right I changed the folder structure and naming convention and automatize publishing tasks.
You should now have all changes within the CHANGELOG file each time a create a new version.
But I'm sorry I might have messed up with the major/minor version changes.
I did those changes to try to optimize the development workflow and I need some time to get used to it.

**Comment by rathpc** [comment]
No worries, I just think it might be helpful to mention this breaking change somewhere since it isn't very clear otherwise when it happened since there is no reference to 0.2.1 on github any longer or in CHANGELOG. Thanks.
