### ISSUE TITLE
feature: configure delimiter keys

### ISSUE THREAD

**Issue by matryer** [Wikiki/bulma-tagsinput#22]
I'd like to be able to specify which keys are delimiters. For example, I want the `SPACE` character to indicate a new tag.

```
<input class="input" type="tags" placeholder="Add Tag" value="Tag1,Tag2,Tag3" data-tags-delimiters="enter,space,comma">
```

**Comment by agitude** [comment]
so can SPACE indicate a new tag and at the same time 'approve' the previous tag?

**Comment by matryer** [comment]
Yeah it's an option. I suppose some people would want spaces in their tags, but for cases like Twitter, Instagram, etc. where hashtags are unbroken strings, hitting space ends the tag.

**Comment by matryer** [comment]
@Wikiki What do you think about this?

**Comment by matryer** [comment]
I figured out how to do this. It would be great if it was documented. Great library btw.

**Comment by Wikiki** [comment]
Hi,

you're right I forgot to document it.
I have a global work to do on documentation on each extension.
