### ISSUE TITLE
Not working, no documentation

### ISSUE THREAD

**Issue by mokhosh** [Wikiki/bulma-tagsinput#24]
I installed tagsinput, imported js and scss and added a `type=tags` input, but it's just a simple text input:

```
import 'bulma-tagsinput/dist/bulma-tagsinput.min'

@import "~bulma-tagsinput";

<input class="input" type="tags" placeholder="Add Tag" value="Tag1,Tag2,Tag3">
```

**Comment by Wikiki** [comment]
Hi, the documentation is outdated. Please call the <code>.attach()</code> static method to init the plugin on the input.

I'm currently working on the big issue with the integration into Laravel then I'll update all extensions and documentation.
Sorry for the inconvenience.

**Comment by mokhosh** [comment]
I tried this:
```
import Tagify from 'bulma-tagsinput/dist/bulma-tagsinput.min'

document.addEventListener('DOMContentLoaded', function () {
    Tagify.attach()
})
```
but i get `Tagify is not defined` in the console.

also, i'm currently using this in a Laravel project, can you tell me what exactly you're working on?

**Comment by Wikiki** [comment]
I'm currently working with another user on is issue with laravel integration and I found the following process to follow to get it work (for carousel extension):

1. add "laravelcollective/html": "5.*" to composer.json then run "composer update"

2. in app.php: add this provider: Collective\Html\HtmlServiceProvider::class,

3. then these aliases:
     'HTML' => Collective\Html\HtmlFacade::class,
     'Form' => Collective\Html\FormFacade::class

4. in webpack.mix.js update the mix command to:
     mix.js('resources/assets/js/app.js', 'public/js')
            .sass('resources/assets/sass/app.scss', 'public/css')
            .copy('node_modules/bulma-carousel/dist/bulma-carousel.js', 'public/js');

5. in your view (welcome.blade.php) add the following at the end:
     {!! HTML::script('js/bulma-carousel.js') !!}
        <script>
        var carousels = bulmaCarousel.attach();
        </script>

**Comment by Wikiki** [comment]
you should have bulmaTagsinput defined, not Tagify

**Comment by mokhosh** [comment]
```
import bulmaTagsinput from 'bulma-tagsinput/dist/bulma-tagsinput.min'

document.addEventListener('DOMContentLoaded', function () {
    bulmaTagsinput.attach()
})
```
Console:
```
ReferenceError: bulmaTagsinput is not defined
```

**Comment by mokhosh** [comment]
i import `bulma-tagsinput.min.js` in my `app.js` file. because it's better to have a single js file and a single request. it shouldn't be any different, right?

**Comment by Wikiki** [comment]
Yes it should. if you are using laravel you should use mix instead to import modules from node_modules.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by Wikiki** [comment]
You issue is related to Laravel integration so I only know 2 ways for it to work:
1. Use the flow I gave you
2. Recompil sources by yourself with your own webpack configuration

Regards

**Comment by mokhosh** [comment]
Thank you

The first option is not an option for me because I have to keep my requests minimal.
I don't know how to do the second option.

Here's how I made it work for now. I moved my `attach()` call to `app.js` instead of the page where I need it. The downside is it will be called in every page.

Looking forward to the Laravel integration.

**Comment by mokhosh** [comment]
Isn't that what `import` should do?
I'm also using `sweetalert` and it works in all files just fine without making a new global variable.

**Comment by Wikiki** [comment]
I'll try to have a look at sweetalert to check what's different.
Can you please give me the sweetalert repo url to be sure to look at the right one ?

**Comment by mokhosh** [comment]
Sure:

https://github.com/t4t5/sweetalert
https://sweetalert.js.org/docs/

Thank you

**Comment by Wikiki** [comment]
Thanks. I'll keep you in touch

**Comment by Wikiki** [comment]
Can you please try with the last commit ?
https://github.com/Wikiki/bulma-tagsinput/blob/master/dist/js/bulma-tagsinput.js

**Comment by mokhosh** [comment]
I replaced the bulma-tagsinput line in my final compiled file with the new `.min.js` file and I got the same error.

**Comment by mokhosh** [comment]
I get `bulmaTagsinput is not defined`.
To be fair I copied the code to my final compiled file since I didn't know how to use the latest commit without upgrading the npm package. Could that be the problem?

**Comment by Wikiki** [comment]
no that's the right way.
I don't understand why it's not working with "import" :-(

**Comment by mokhosh** [comment]
Thanks anyway.
Maybe we can fix this later.

**Comment by Wikiki** [comment]
I think this is a case issue: try both: bulmaTagsinput and bulmaTagsInput (i of input in lower and upper case)

**Comment by mokhosh** [comment]
Tried both. No luck.

**Comment by Wikiki** [comment]
please try last release

**Comment by Wikiki** [comment]
please try last release

**Comment by jmaczan** [comment]
Hello @mokhosh, did you find out a way to run tags?

**Comment by mohamdio** [comment]
Just do that:

```
// Initialize all input of tags type.
var tagsinput = bulmaTagsinput.attach('[type="tags"]');
```

**Comment by pdiveris** [comment]
Thank you mohamdio!
