### ISSUE TITLE
How to restart tags (in Vuejs)

### ISSUE THREAD

**Issue by ambrt** [Wikiki/bulma-tagsinput#26]
I got working tagsinput in Vuejs.

I populate tags and start the instance with
`new Tagify(document.getElementById('mytags'))`

and tags show up.

Now i try to change the value programmatically and i can confirm that value of input changed
`$vm0.$el.querySelector(".input").value`
 but tags did not.

How can i refresh those tags after value change?

**Comment by Wikiki** [comment]
Try calling

```
TAGSINPUT_INSTANCE.savePartial($vm0.$el.querySelector(".input").value);
```

**Comment by ambrt** [comment]
savePartial is adding new tag to already existing ones. I need to change tags.

**Comment by Wikiki** [comment]
So I have to add a refresh method. I'll try to work on it this weekend.

**Comment by nicostuhlfauth** [comment]
@ambrt I use Vuejs with Typescript, and try to get bulma-tagsinput running. What I already tried:

1. Installed bulma-tagsinput with yarn
2. Added SCSS import statement directly after importing Bulma: `@import "node_modules/bulma-tagsinput/dist/css/bulma-tagsinput";`
3. Imported JS: `import bulmaTagsInput from '../node_modules/bulma-tagsinput/dist/js/bulma-tagsinput.min.js';`

Any idea?

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
