### ISSUE TITLE
Not working (using "bulma-extensions": "^2.2.1")

### ISSUE THREAD

**Issue by Ryozuki** [Wikiki/bulma-tagsinput#27]
It shows normal text instead of the tags

**Comment by AnaXaX** [comment]
`var Tagify = require("bulma-extensions/bulma-tagsinput/dist/js/bulma-tagsinput")
document.addEventListener('DOMContentLoaded', function () {
    Tagify.attach()
})`

**Comment by healthcareguy** [comment]
Has this been fixed?

**Comment by healthcareguy** [comment]
In case anyone needs help - just add 
bulmaTagsinput.attach();
to  your main.js
