### ISSUE TITLE
How do you get this to work?

### ISSUE THREAD

**Issue by RTK99** [Wikiki/bulma-tagsinput#28]
Followed the guide, and I compiled the tags into my scss. I also imported the JS script like so.
```js
<script src="https://cdn.jsdelivr.net/npm/bulma-extensions@2.2.1/bulma-tagsinput/dist/js/bulma-tagsinput.js"></script>
```
Yet the tags input just shows a string. How should I go about fixing this?

**Comment by Wikiki** [comment]
Hi,

just call <code>bulmaTagsinput.attach();</code> into your main JS file.

**Comment by RTK99** [comment]
Okay thank you very much. On a side note, is there a specific way to style
the input box that you'd type into? All the ways I've tried have not worked
and it leads to to believe I have to do it differently.

On Aug 16, 2018 5:47 PM, "Wikiki" <notifications@github.com> wrote:

Hi,

just call bulmaTagsinput.attach(); into your main JS file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wikiki/bulma-tagsinput/issues/28#issuecomment-413694837>,
or mute the thread

**Comment by Wikiki** [comment]
You can play with the procided .css file to change the style
