### ISSUE TITLE
Tags don't respond to clicks on mobile devices?

### ISSUE THREAD

**Issue by Texlo-Dev** [Wikiki/bulma-tagsinput#29]
So I've gotten the tags working in my desktop browser. However, when I switch over to my phone, and try them, I cannot seem to click the "x" to delete them, but I can add them. Is this an issue with the extension? Or an issue on my part?

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
