### ISSUE TITLE
Can't create a tag with comma

### ISSUE THREAD

**Issue by Wavum** [Wikiki/bulma-tagsinput#3]
Can't create a tag with comma which is also possible with [tags-input](https://github.com/developit/tags-input). For example, ```test,``` should create a tag.

**Comment by Wikiki** [comment]
Hi @Wavum,

If you try to add following tags <code>Tag 8, Tag 9, Tag 10</code> then press enter on the demo it's working as expecting.

Regards

**Comment by Wikiki** [comment]
It has been fixed.
