### ISSUE TITLE
Delete and Set Tags Input programmatically

### ISSUE THREAD

**Issue by FuelKubitox** [Wikiki/bulma-tagsinput#31]
I tried everything, but i cant solve it. I use Angular and i tried on many Ways to delete or set the Tags in my Code, but i just found no Way.
Is there a Way to reset or add Tags in Code? Maybe someone has an Example.

**Comment by Wikiki** [comment]
Hi,

you can use the ```addTag($text)``` method.
Call it on a tagsInput instance (remember attach() method returns an array of all instances)
