### ISSUE TITLE
Any compat with Typedhead ?

### ISSUE THREAD

**Issue by louia** [Wikiki/bulma-tagsinput#32]
Any compat with Typedhead autocomplete like on bootstrap  or on this demo : https://voerro.github.io/vue-tagsinput/ ??

**Comment by Wikiki** [comment]
Hi,

not yet but it's in the ToDo.

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities like typehead compatibility available here: https://github.com/CreativeBulma/bulma-tagsinput
