### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by EnderDev** [Wikiki/bulma-tagsinput#33]
Hi I am getting this "error" on the TagInput extension, the extension works fine it's just this annoying message appears in console, and I have no idea why. Seems like a syntax error.

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
