### ISSUE TITLE
Input field isn't centered

### ISSUE THREAD

**Issue by raphael-gosteli** [Wikiki/bulma-tagsinput#34]
When entering a tag the input field isn't centered anymore.

![Unbenannt](https://user-images.githubusercontent.com/31771989/54981355-617a0f00-4fa8-11e9-8f87-a2fdfed8cef1.PNG)

# HTML
```html
<p class="control has-icons-left">
	<input class="input" type="tags" placeholder="Add a tag" value="">
	<span class="icon is-small is-left">
              <i data-feather="tag"></i>
        </span>
</p>
```

# CSS

No additional css

**Comment by Wikiki** [comment]
Hi,

it's weird cause the input field shouldn't even be visible. All bulma/browser default style should be overriden to remove any style from it.
Can you please check you don't have conflict on CSS ?
