### ISSUE TITLE
Feature request: Allow support for Bulma size modifiers

### ISSUE THREAD

**Issue by RobChooses** [Wikiki/bulma-tagsinput#36]
Allow Bulma size modifiers (`is-small`, `is-medium`, `is-large`) on `tag` and group size modifiers (`are-medium`) on `tags`.

Perhaps these could be added via dataset options, such as `data-size="is-medium"`?

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
