### ISSUE TITLE
Tag Appearance Not Like Documentation

### ISSUE THREAD

**Issue by c0rndogs** [Wikiki/bulma-tagsinput#38]
Hi, when I enter tags into an input field, there is basically no left and right padding and the "delete" button is not there.
![image](https://user-images.githubusercontent.com/15634600/59153222-b6f78100-8a19-11e9-9ee2-3de360a699b5.png)
I've tried messing with the CSS directly and I've noticed that attributes like border-radius respond, but margins don't and I have no idea how to get the little "delete button to show up.

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
