### ISSUE TITLE
Text Area for Tags is offset to the bottom

### ISSUE THREAD

**Issue by uhteddy** [Wikiki/bulma-tagsinput#39]
Whenever I use it the input area is at the bottom.

![image](https://user-images.githubusercontent.com/54421295/64479487-e1c2b400-d185-11e9-8c4d-95c28e00207b.png)

Another issue I'm getting is that there is an outline to the input as well. 
![image](https://user-images.githubusercontent.com/54421295/64479499-0585fa00-d186-11e9-849d-10095bfb2cc2.png)

**Comment by tadeoos** [comment]
Same here. I'm using Firefox.

**Comment by tadeoos** [comment]
@Wikiki any plans on fixing this? I'd love to help, but I'm more of a Python coder...

**Comment by moomoohk** [comment]
Hi. I would like to fix this issue myself and open a pull request. Are the maintainers still active?

**Comment by moomoohk** [comment]
I inspected tags and compared their CSS with the problematic input field and here are my findings:
* Setting the `control` class on the input field applies great CSS rules which fix the issue but when you type the input's width will change, which isn't ideal
* The `control` class applies `margin-bottom: 12px` to any element (among other rules) so I manually applied the `margin-bottom` rule to the input and that does the trick

If this repo is being actively maintained I will put together a pull request

**Comment by Wikiki** [comment]
Hi,

please use the new version including a lot of bug fixes and new functionalities available here: https://github.com/CreativeBulma/bulma-tagsinput
