### ISSUE TITLE
Tag selecting of key events is not working properly

### ISSUE THREAD

**Issue by schleimschein** [Wikiki/bulma-tagsinput#7]
### Issue
Tag selection of the following keyevents isn't working properly: Backspace, Delete, ArrowKeys
In detail:
- After the backspace key event - deleting a selected tag - the tag left to the deleted tag isn't selected. Instead no tag is selected.
- After the delete key event - deleting a selected tag - the tag right to the deleted tag isn't selected. Instead no tag is selected.
- The arrow key events - selecting a tag left or right -  are not working at all. 

### Possible Fix
The JS commands `selectedTag.nextSibling` (`selectedTag.previousSibling`) doesn't yield the sibling `span.tag` element but the sibling `div.control` element which posses the `span.tag` in second order as a child knot. It was sufficient for me to change in tagsinput.js all `select` commands from
`this.select(selectedTag.nextSibling);`
(`this.select(selectedTag.previousSibling);`
to
`this.select($(selectedTag.nextSibling).find('span').get(0));`
(`this.select($(selectedTag.previousSibling).find('span').get(0));`)

**Comment by Wikiki** [comment]
Fixed by #4d37ea5
