### ISSUE TITLE
Selected tag isn't highlighted

### ISSUE THREAD

**Issue by schleimschein** [Wikiki/bulma-tagsinput#8]
### Issue
For Bulma 0.6.1 selected tags aren't highlighted.

### Possible fix
The bulma css class modifier `is-active` doesn't exist for the class `tag`. Changing all `is-active`  occurences in tagsinput.js to any valid tag class modifier, e.g. `is-primary`, seems to do the job.

**Comment by Wikiki** [comment]
Fixed by #4d37ea5
