### ISSUE TITLE
Input line behaving strangely for Bulma 0.6.1

### ISSUE THREAD

**Issue by schleimschein** [Wikiki/bulma-tagsinput#9]
### Issue
The input line is not rendered properly by Bulma 0.6.1: The  input line ( and following the form field itself) are displayed in the size of `is-small` despite `is-normal` being the default. Also, before the first key event, the input line isn't filling the whole form field  - In my case only about the width of a column of the size `one-fifth`.

### Possible Fix
I fixed the problem by explicitly declaring the class name of the input element in tagsinput.js
`this.input.className = 'input';`
after the instantiation of the input element in the`init()` function
`this.input = document.createElement('input');` .

**Comment by Wikiki** [comment]
Adding 'input' class to this.input add style to the input but it should stay invisible for the user (the container visually replace the input element)

**Comment by schleimschein** [comment]
Ok! Maybe a comment in the code would clarify this?

**Comment by Wikiki** [comment]
Fixed by #f6b02c1.

Once again: thank you very much for all your contributions
